### ISSUE TITLE
authentication not working when forcing authentication

### ISSUE THREAD

**Issue by tavikukko** [koltyakov/sp-auth-electron-sample#1]
Hi @koltyakov 
and thanks for this great sample.
When setting "force": true on the auth setting, the authentication flow hangs. Any idea?
using macOS, seems to work on windows.
```
{
  "siteUrl": "https://contoso.sharepoint.com",
  "strategy": "OnDemandCredentials",
  "ondemand": true,
  "force": true,
}
```

**Comment by koltyakov** [comment]
Hi Tomi,

I didn't check this settings combination in macOS. Will do sooner when macOS machine will be at hand.

**Comment by tavikukko** [comment]
The problem seems to be that the auth pop-up window does not get closed. When forcing close (pressing x from the pop-up), the app continues and works normally. So I think this is node-sp-auth problem.

**Comment by koltyakov** [comment]
Oh, I even missed it was opened.
